apiVersion: apps/v1
kind: Deployment
metadata:
  name: pybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pybot
  template:
    metadata:
      labels:
        app: pybot
    spec:
      containers:
        - name: pybot
          image: edwardlol/pybot:latest
          args:
            - --host
            - "0.0.0.0"
            - --port
            - "8000"
          envFrom:
            - configMapRef:
                name: pybot
            - secretRef:
                name: pybot
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "1"
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
          volumeMounts:
            - name: shared-vol
              mountPath: /mnt/shared
              readOnly: false
      volumes:
        - name: shared-vol
          nfs:
            server: 10.0.0.29
            path: /data/pybot/shared
