apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: pybot
      app.kubernetes.io/name: pybot
      app.kubernetes.io/version: 7ab4052
      app.kubernetes.io/managed-by: kubectl
    includeSelectors: false

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: pybot
    envs:
      - params.env

# currently knative does not recognize configmaps with suffix hash
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: edwardlol/pybot
    newTag: 7ab4052
