apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pybot
spec:
  gateways:
    - istio-system/istio-ingressgateway
  hosts:
    - pybot.agi.zjuici.com
  http:
    - name: pybot-oauth2-proxy-route
      match:
        - uri:
            prefix: /oauth2/
      route:
        - destination:
            host: oauth2-proxy
            port:
              number: 8080
    - name: pybot-route
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: pybot
            port:
              number: 8000
