apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pybot
spec:
  template:
    spec:
      containers:
        - image: edwardlol/pybot:latest
          args:
            - --host
            - "0.0.0.0"
            - --port
            - "8000"
          envFrom:
            - configMapRef:
                name: pybot
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "1"
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
