apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-gateway
  namespace: jupyter
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: enterprise-gateway
          # Setting args `--FileKernelSessionManager.persistence_root` does not work, so I need to set the environment variables directly
          # And as the env is a list, kustomize cannot perform replace value by name, I need to copy the whole env list here
          env:
          - name: EG_PORT
            value: "8888"
          - name: EG_RESPONSE_PORT
            value: "8877"
          - name: EG_NAMESPACE
            value: jupyter
          - name: EG_KERNEL_CLUSTER_ROLE
            value: kernel-controller
          - name: EG_SHARED_NAMESPACE
            value: "False"
          - name: EG_MIRROR_WORKING_DIRS
            value: "False"
          - name: EG_CULL_IDLE_TIMEOUT
            value: "3600"
          - name: EG_CULL_CONNECTED
            value: "False"
          - name: EG_LOG_LEVEL
            value: DEBUG
          - name: EG_KERNEL_LAUNCH_TIMEOUT
            value: "60"
          - name: EG_KERNEL_INFO_TIMEOUT
            value: ""
          - name: EG_ALLOWED_KERNELS
            value: '["r_kubernetes","python_kubernetes","python_tf_kubernetes","python_tf_gpu_kubernetes","scala_kubernetes","spark_r_kubernetes","spark_python_kubernetes","spark_scala_kubernetes","spark_python_operator"]'
          - name: EG_DEFAULT_KERNEL_NAME
            value: python_kubernetes
          - name: EG_INHERITED_ENVS
            value: PATH
          # 2 envs related to session persistence
          - name: EG_KERNEL_SESSION_PERSISTENCE
            value: "True"
          - name: EG_PERSISTENCE_ROOT
            value: /data
          volumeMounts:
            - name: persistence-root
              mountPath: /data
              readOnly: false
      volumes:
        - name: persistence-root
          persistentVolumeClaim:
            claimName: persistence-root
