apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jupyter-enterprise-gateway.yaml

patches:
  - path: patches/patch-service.yaml
  - path: patches/patch-kip-container-runtime.yaml
